- name: Create Instance
  hosts: localhost
  vars_files:
      - "vars/credentials.yaml"
  tasks:
    - name: Create a new instance 
      os_server:
        auth: "{{ credentials }}"
        state: present
        name: rhel-8.2-builder
        #image: 
        boot_volume: rhel-8.2-iso-bootable
        volumes:
          - rhel-8.2-iso-builder
        timeout: 200
        flavor: m1.medium
        auto_ip: no
        #network: admin-net
        nics:
          - net-name: admin-net
          #- net-id: 34605f38-e52a-25d2-b6ec-754a13ffb723
