- name: Prepare OpenStack Network
  hosts: localhost
  vars_files:
    - "vars/credentials.yaml"
    - "vars/config-data.yaml"
  tasks:
    - name: Create Public/Provider Network
      os_network:
        state: present
        project: "{{ item.project }}"
        name: "{{ item.name }}"
        admin_state_up: yes
        external: yes
        #mtu_size: 8942
        provider_network_type: "{{ item.provider_network_type }}"
        provider_physical_network: "{{ item.provider_physical_network }}"
        #provider_segmentation_id: "{{ external_seg }}"
        #region_name: regionOne
        #dns_domain: openstack.local
        shared: no
      with_items:
        - "{{ ext_net }}"

    - name: Create Public/Provider Subnet
      os_subnet:
        state: present
        name: "{{ item.name }}"
        network_name: "{{ item.network_name }}"
        ip_version: '4'
        #project: admin
        #region_name: regionOne
        cidr: "{{ item.cidr }}"
        gateway_ip: "{{ item.gateway_ip }}"
        dns_nameservers: "{{ item.dns_nameservers }}"
        allocation_pool_start: "{{ item.allocation_pool_start }}"
        allocation_pool_end: "{{ item.allocation_pool_end }}"
      with_items:
        - "{{ ext_sub }}"

    - name: Create Tenant Network
      os_network:
        state: present
        #project: admin
        name: "{{ item.name }}"
        admin_state_up: yes
        #external: yes
        #mtu_size: 8942
        #provider_network_type: flat
        #provider_physical_network: datacentre
        #provider_segmentation_id: 0
        #region_name: regionOne
        #dns_domain: openstack.local
        shared: no
      with_items:
        - "{{ int_net }}"

    - name: Create Tenant Subnet
      os_subnet:
        state: present
        name: "{{ item.name }}"
        network_name: "{{ item.network_name }}"
        ip_version: '4'
        #project: admin
        #region_name: regionOne
        cidr: "{{ item.cidr }}"
        gateway_ip: "{{ item.gateway_ip }}"
        dns_nameservers: "{{ item.dns_nameservers }}"
        allocation_pool_start: "{{ item.allocation_pool_start }}"
        allocation_pool_end: "{{ item.allocation_pool_end }}"
      with_items:
        - "{{ int_sub }}"

    - name: Create Tenant Router
      os_router:
        state: present
        #project: admin
        #region_name: regionOne
        name: "{{ item.name }}"
        admin_state_up: yes
        network: "{{ item.network }}"
        external_fixed_ips: "{{ item.external_fixed_ips }}"
        enable_snat: yes
        interfaces: "{{ item.interfaces }}"
      with_items:
        - "{{ router_info }}"
