---
  - name: List Task Template
    find:
      paths: "{{ playbook_dir }}/tasks"
      patterns: "02-0[2-4]-*"
      use_regex: yes
    register: task_files

  - name: Setup Template for CREATE Action
    replace:
      path: "{{ item.path }}"
      backup: no
      regexp: "Delete"
      replace: "Create"
    with_items:
      - "{{ task_files.files }}"
    no_log: yes

  - name: Setup Template for CREATE Action
    replace:
      path: "{{ item.path }}"
      backup: no
      regexp: "absent"
      replace: "present"
    with_items:
      - "{{ task_files.files }}"
    no_log: yes
