---
  - name: List Task Template
    find:
      paths: "{{ playbook_dir }}/tasks"
      patterns: "02-0[2-4]-*"
      use_regex: yes
    register: task_files

  - name: Setup Template for DELETE Action
    replace:
      path: "{{ item.path }}"
      backup: no
      regexp: "Create"
      replace: "Delete"
    with_items:
      - "{{ task_files.files }}"
    no_log: true

  - name: Setup Template for DELETE Action
    replace:
      path: "{{ item.path }}"
      backup: no
      regexp: "present"
      replace: "absent"
    with_items:
      - "{{ task_files.files }}"
    no_log: true
