---
  - name: Create a Secgroup
    os_security_group:
      auth: "{{ credentials | default(omit) }}"
      state: present
      #project: admin
      name: sg-1
      description: "Security Group"

  - name: Create Secgroup Rules
    os_security_group_rule:
      auth: "{{ credentials | default(omit) }}"
      state: present
      #project: admin
      security_group: sg-1
      protocol: "{{ item.protocol }}"
      ethertype: IPv4
      direction: ingress
      port_range_min: "{{ item.port_min | default(omit) }}"
      port_range_max: "{{ item.port_max | default(omit) }}"
      # remote_group: default
      remote_ip_prefix: "{{ item.source }}"
    loop:
      - protocol: icmp
        source: 0.0.0.0/0
      - protocol: tcp
        port_min: 22
        port_max: 22
        source: 0.0.0.0/0
      - protocol: tcp
        port_min: 80
        port_max: 80
        source: 0.0.0.0/0


