---
  - name: Create a new instance 
    os_server:
      auth: "{{ credentials | default(omit) }}"
      state: present
      name: vm-2
      image: CentOS-7
      # boot_volume: rhel-8.2-iso-bootable
      # volumes:
        # - rhel-8.2-iso-builder
      timeout: 200
      flavor: c01m010
      auto_ip: no
      #network: admin-net
      nics:
        - net-name: admin-net
        #- net-id: 34605f38-e52a-25d2-b6ec-754a13ffb723
