- name: Prepare OpenStack Network
  hosts: localhost
  vars_files:
    - "vars/credentials.yaml"
    - "vars/config-data.yaml"
  tasks:
    - name: Create Public/Provider Network
      include_tasks: "tasks/01-00-provider-network.yaml"

    - name: Create Tenant Network
      include_tasks: "tasks/01-01-tenant-network.yaml"

    - name: Create Tenant Router
      include_tasks: "tasks/01-02-tenant-router.yaml"
