- name: Prepare OpenStack Network
  hosts: localhost
  vars_files:
    - "vars/credentials.yaml"
    - "vars/config-data.yaml"
  vars:
    deploytype: "CREATE"
    task_lists:
      - "tasks/02-02-provider-network.yaml"
      - "tasks/02-03-tenant-network.yaml"
      - "tasks/02-04-tenant-router.yaml"
  tasks:
    - name: Prepare CREATE OpenStack Network
      include_tasks: "tasks/02-00-prepare-create.yaml"
      when: deploytype=="CREATE"

    - name: Create OpenStack Network
      vars:
        task_name: "{{ main_item }}"
      include_tasks: "{{ task_name }}"
      with_items:
        - "{{ task_lists }}"
      loop_control:
        loop_var: main_item
      when: deploytype=="CREATE"

    - name: Prepare DELETE  OpenStack Network
      include_tasks: "tasks/02-01-prepare-delete.yaml"
      when: deploytype=="DELETE"

    - name: Delete OpenStack Network
      vars:
        task_name: "{{ main_item }}"
      include_tasks: "{{ task_name }}"
      with_items:
        - "{{ task_lists[::-1] }}"
      loop_control:
        loop_var: main_item
      when: deploytype=="DELETE"

