- name: Instance Action
  hosts: localhost
  vars_files:
      - "vars/credentials.yaml"
  tasks:
    - name: Shutdown Instance
      os_server_action:
        auth: "{{ credentials }}"
        action: stop
        server: rhel-8.2
        timeout: 200
